name: CatchTheTail
version: '1.0-SNAPSHOT'
main: org.foodust.catchTheTail.CatchTheTail
api-version: '1.21'
authors: [ Foodust ]
description: Catch The Tail
website: http://github.com/foodust/CatchTheTail
libraries:
  - "net.kyori:adventure-api:4.19.0"
  - "net.kyori:adventure-platform-bukkit:4.3.4"
  - "net.kyori:adventure-text-minimessage:4.19.0"
commands:
  꼬리잡기: